# Top-level Makefile
# Builds everything: planet, Python interface and CLI interface

CC     = /usr/lib/ggdb
CFLAGS = -Wall -fPIC -std=c++11 -Ilib -Iplanet -Itinyxml2 -fopenmp


# Common files for the shared lib (libatnept.a)
LIB_OBJ = lib/Array.o lib/Array_2D.o lib/Array_1D.o lib/Config.o lib/Utils.o lib/FFT.o

ATNEPT_OBJ = planet/cNeptuneModel.o planet/PrintMsg_Nept.o planet/RungeKutta_Nept.o \
planet/RHS_Nept.o planet/BC_Nept.o planet/ParaView_Nept.o planet/Thermo_Nept.o \
planet/SaturationAdjustmentNept.o planet/Chemistry_Nept.o \
planet/InitVariables_Nept.o planet/FileIO_Nept.o

XML_OBJ = tinyxml2/tinyxml2.o

# Command line objects
ATNEPT_CLI_OBJ = cli/nept.o cli/DefaultStream.o

# Because there are so many parameters, many of the files are autogenerated
PARAM_OUTPUTS = planet/cNeptuneDefaults.cpp.inc planet/NeptuneLoadConfig.cpp.inc \
planet/NeptuneParams.h.inc neptune/config_atnept.xml python/neptune_pxd.pxi python/pyatnept.pyx

#copy pyatnept.so from python dir to neptune dir
COPY_FILE = pyatnept.so
TARGET_DIR = neptune

target = $(addprefix $(TARGET_DIR)/,$(COPY_FILE))

all: nept python $(target)

libatnept.a: $(PARAM_OUTPUTS) $(LIB_OBJ) $(ATNEPT_OBJ) $(XML_OBJ)
	ar rcs libatnept.a $(LIB_OBJ) $(ATNEPT_OBJ) $(XML_OBJ)

nept: libatnept.a $(ATNEPT_CLI_OBJ)
	$(CXX) $(CFLAGS) $(ATNEPT_CLI_OBJ) -L. -latnept $(LDFLAGS) -o cli/nept

$(PARAM_OUTPUTS): param.py
# explicitly clean dependent files
	rm -f planet/cNeptuneModel.o
	python3 param.py

analyze:
	analyze-build make

python: libatnept.a python/pyatnept.so

python/pyatnept.so: python/pyatnept.pyx python/atnept.pxd libatnept.a
	cd python && python3 setup.py build_ext --inplace

# copy pyatnept.so from python dir to neptune dir
$(TARGET_DIR)/pyatnept.so: python/pyatnept.cpython-310-x86_64-linux-gnu.so
	cp $< $@


planet/%.o: planet/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

lib/%.o: lib/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

cli/%.o: cli/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

tinyxml2/%.o: tinyxml2/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CFLAGS) -c $<

.PHONY: clean
clean:
	\rm -vf $(LIB_OBJ) $(ATNEPT_OBJ) $(XML_OBJ) $(ATNEPT_CLI_OBJ) $(PARAM_OUTPUTS) nept libatnept.a
	\rm -vf python/*.so python/*.o python/pyatnept.cpp
	\rm -rf python/build/
